services:
  rethinkdb:
    image: rethinkdb
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"
    volumes:
      - /data:/data]
    command: rethinkdb --bind all --data /data 

app:
  image: jeromesmiths/intelli-vasapi
  ports:
    - "8888:8888"
  volumes:
    - ./app:/src
  working_dir: /src
  command: npm vasapiServer
  depends_on: rethinkdb